/* =====================================================================
   Receitas operacionais — geradas automaticamente a partir do histórico
   de 370 registros de pedidos (dados.json).
   Quantidades derivadas da mediana real de compras para 65 pessoas.
   NÃO edite manualmente — regenere com: node scripts/gerar-receitas.js
   ===================================================================== */

import type { Receita } from './receitas';

export const RECEITAS_OPERACIONAIS: Receita[] = [
  {
    nome: "Almondegas á Parmegiana",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Almondegas ao molho",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.015 },
      { item: "Purê de batata", unid: "pct", porPessoa: 0.031 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.015 },
      { item: "Agrião", unid: "mç", porPessoa: 0.108 },
      { item: "Cebola", unid: "kg", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Flan", unid: "pct", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Almondegas ao molho com manjerição",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.031 },
      { item: "Manjericão", unid: "mç", porPessoa: 0.015 },
      { item: "Pure de Batata Pronto", unid: "un", porPessoa: 0.031 },
      { item: "Alface americano", unid: "un", porPessoa: 0.092 },
      { item: "Manga", unid: "un", porPessoa: 0.077 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.123 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Almondegas ao molho de manjerição",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Manjericão", unid: "g", porPessoa: 0.769 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046, opcional: true },
      { item: "Manga", unid: "un", porPessoa: 0.062, opcional: true },
      { item: "Abacaxi", unid: "un", porPessoa: 0.092, opcional: true },
      { item: "Alface", unid: "un", porPessoa: 0.062, opcional: true },
    ],
  },
  {
    nome: "Almondegas ao molho de tomate com Manjerição",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.108 },
      { item: "Molho de tomate", unid: "lt", porPessoa: 0.046 },
      { item: "Manjericão", unid: "mç", porPessoa: 0.015 },
      { item: "Alface americano", unid: "un", porPessoa: 0.123 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Baião de Dois, lombo suíno",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Feijão Fraldinha", unid: "kg", porPessoa: 0.062 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Couve", unid: "un", porPessoa: 0.123 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
      { item: "Leite condensado", unid: "un", porPessoa: 0.015 },
      { item: "Creme de Leite", unid: "un", porPessoa: 0.015 },
      { item: "Gelatina de Morango", unid: "un", porPessoa: 0.015 },
      { item: "suco de morango calda", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Bife a Role",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Batata doce", unid: "kg", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062, opcional: true },
    ],
  },
  {
    nome: "Bife acebolado",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.277 },
      { item: "Pure de Batata Pronto", unid: "pct", porPessoa: 0.031 },
      { item: "Repolho", unid: "un", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Bife acebolado (patinho fatiado)",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Abacate maduro", unid: "un", porPessoa: 0.092 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.015 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.062 },
      { item: "Pepino", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Bife ao Creme de Batata",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Brocolis Ninja", unid: "un", porPessoa: 0.092 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Suco de maracujá", unid: "pct", porPessoa: 0.015 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
      { item: "Fritas", unid: "kg", porPessoa: 0.077 },
      { item: "Acelga", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Bife ao Molho",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.031, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.062, opcional: true },
    ],
  },
  {
    nome: "Bife de patinho",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.277 },
      { item: "Batata doce", unid: "kg", porPessoa: 0.062 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Alface americana", unid: "un", porPessoa: 0.092 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
      { item: "Abacate maduro", unid: "un", porPessoa: 0.092 },
    ],
  },
  {
    nome: "Bisteca com Barbecue",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Milho Verde-", unid: "un", porPessoa: 0.015 },
      { item: "Repolho roxo-", unid: "un", porPessoa: 0.062 },
      { item: "Cenoura-", unid: "kg", porPessoa: 0.031 },
      { item: "Abacaxi maduro-", unid: "un", porPessoa: 0.123 },
    ],
  },
  {
    nome: "Bisteca com Molho Barbecue",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Banana da Terra madura", unid: "un", porPessoa: 0.369 },
      { item: "Alface americano", unid: "un", porPessoa: 0.092 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Maçã", unid: "un", porPessoa: 1.077 },
      { item: "Barbecue", unid: "lt", porPessoa: 0.015 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Bisteca em Tiras no Limão",
    categoria: "principal",
    rendimento: 65,
    ingredientes: [
      { item: "Limão", unid: "un", porPessoa: 0.154 },
      { item: "Abóbora", unid: "un", porPessoa: 0.015 },
      { item: "Repolho", unid: "un", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Curau", unid: "pct", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Calabresa Frita Com Cebola",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Cebola", unid: "kg", porPessoa: 0.046 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
      { item: "Calabresa Frita", unid: "kg", porPessoa: 0.308 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Pimentão", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Carne Assada",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Batata doce", unid: "kg", porPessoa: 0.077 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Creme culinário", unid: "lt", porPessoa: 0.031 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Carne Assada com Molho Champion",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Champion", unid: "pct", porPessoa: 0.062 },
      { item: "Molho madeira", unid: "lt", porPessoa: 0.015 },
      { item: "Batata", unid: "kg", porPessoa: 0.154 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.092 },
      { item: "Alecrim", unid: "mç", porPessoa: 0.015 },
      { item: "Mazeina", unid: "cx", porPessoa: 0.015 },
      { item: "bolacha", unid: "pct", porPessoa: 0.154 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
      { item: "Chocolate", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Carne cozida com Abobora",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Abóbora", unid: "un", porPessoa: 0.046 },
      { item: "Repolho", unid: "un", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.031 },
      { item: "Maçã", unid: "un", porPessoa: 0.092 },
      { item: "Banana", unid: "un", porPessoa: 0.185 },
      { item: "Maracuja", unid: "un", porPessoa: 0.062 },
      { item: "Manga", unid: "un", porPessoa: 0.123 },
      { item: "Laranja", unid: "un", porPessoa: 0.154 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.015 },
      { item: "Cebola", unid: "kg", porPessoa: 0.015 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Carne de panela",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.077 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.031 },
      { item: "Maçã", unid: "un", porPessoa: 1.077 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.062 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Berinjela", unid: "kg", porPessoa: 0.077 },
    ],
  },
  {
    nome: "Carne de Panela ( Aranha)",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Berinjela", unid: "kg", porPessoa: 0.077 },
      { item: "Mousse morango Pronto", unid: "pct", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Carne de panela Com Batata",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Repolho", unid: "un", porPessoa: 0.031, opcional: true },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Carne de panela com purê de moranga",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Creme culinário", unid: "pct", porPessoa: 0.015 },
      { item: "Leite", unid: "lt", porPessoa: 0.015 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.231 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.108 },
    ],
  },
  {
    nome: "Carne de Panela Desfiada",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.031, opcional: true },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015, opcional: true },
    ],
  },
  {
    nome: "Carne de Panela em cubos com Batata",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Carne Desfiada",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Berinjela comum", unid: "kg", porPessoa: 0.077, opcional: true },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.046 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031, opcional: true },
      { item: "farinha de trigo", unid: "un", porPessoa: 0.031, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.031, opcional: true },
    ],
  },
  {
    nome: "Carne Desfiada Acebolada",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Curau", unid: "pct", porPessoa: 0.015 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Carne em cubos ao molho",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.077 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.046 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Carne em Cubos ao Molho de Tomate",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Carne em Cubos ao Molho madeira",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Pure de Batata ( Pronto)", unid: "pct", porPessoa: 0.031 },
      { item: "Alface", unid: "un", porPessoa: 0.092 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Carne em Cubos com Abobora",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Abobora-", unid: "un", porPessoa: 0.046 },
      { item: "Farinha de mandioca-", unid: "kg", porPessoa: 0.046 },
      { item: "Alface Crespa-", unid: "un", porPessoa: 0.077 },
      { item: "Tomate-", unid: "kg", porPessoa: 0.046 },
      { item: "Mousse de chocolate-", unid: "pct", porPessoa: 0.046 },
      { item: "Leite", unid: "un", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Carne em cubos com molho Madeira",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Molho madeira", unid: "pct", porPessoa: 0.015 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.092 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.077 },
    ],
  },
  {
    nome: "Carne louca",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Brocolis", unid: "un", porPessoa: 0.046 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.092 },
      { item: "Alface americana", unid: "un", porPessoa: 0.108 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Carne Moida a Parmegiana",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.154 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.092 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031 },
      { item: "Leite", unid: "lt", porPessoa: 0.031 },
      { item: "Creme culinário", unid: "cx", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Carne moída com batata",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Farinha de mandioca", unid: "pct", porPessoa: 0.015 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
      { item: "Gelatina de Morango", unid: "pct", porPessoa: 0.015 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Carne Moída Com Batata Doce",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Farinha de mandioca", unid: "pct", porPessoa: 0.015 },
      { item: "Batata doce", unid: "kg", porPessoa: 0.062 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.046 },
      { item: "Suco de morango", unid: "pct", porPessoa: 0.015 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
      { item: "Gelatina", unid: "pct", porPessoa: 0.015 },
      { item: "Molho de tomate", unid: "lt", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Carne Moida com legumes",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.046 },
      { item: "Batata", unid: "kg", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Abóbora", unid: "un", porPessoa: 0.062 },
      { item: "Alface lisa", unid: "un", porPessoa: 0.123 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Pepino", unid: "kg", porPessoa: 0.031 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Leite", unid: "un", porPessoa: 0.015 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
      { item: "Bacon", unid: "kg", porPessoa: 0.015 },
      { item: "Gelatina", unid: "pct", porPessoa: 0.015 },
      { item: "Cebola", unid: "kg", porPessoa: 0.046 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.031 },
      { item: "Molho de tomate", unid: "lt", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Carne moída refogada",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.262 },
      { item: "Pure de Batata Pronto", unid: "pct", porPessoa: 0.031 },
      { item: "Alface", unid: "un", porPessoa: 0.123 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Gelatina", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Carne Moida Refolgada com batata",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Abóbora", unid: "un", porPessoa: 0.062 },
      { item: "Brocolis", unid: "un", porPessoa: 0.123 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Gelatina", unid: "pct", porPessoa: 0.015 },
      { item: "Leite", unid: "lt", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Carreteira de carne desfiada",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Cebolihha", unid: "mç", porPessoa: 0.015 },
      { item: "Brocolis", unid: "un", porPessoa: 0.123 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Mamão", unid: "un", porPessoa: 0.046 },
      { item: "Banana", unid: "un", porPessoa: 0.246 },
      { item: "Laranja", unid: "un", porPessoa: 0.185 },
      { item: "Maçã", unid: "un", porPessoa: 0.092 },
      { item: "Gelatina", unid: "pct", porPessoa: 0.015 },
      { item: "Cebola", unid: "kg", porPessoa: 0.015 },
      { item: "Acelga", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Chuletinha Paulista na Manteiga",
    categoria: "principal",
    rendimento: 65,
    ingredientes: [
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Alecrim", unid: "mç", porPessoa: 0.769 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.092 },
      { item: "Manga", unid: "un", porPessoa: 0.062 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.062 },
      { item: "Bolacha maisena", unid: "pct", porPessoa: 0.031 },
      { item: "Creme culinário", unid: "cx", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Churrasco de Panela — Mandioca frita",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.092 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.077 },
      { item: "Alface", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
      { item: "Melão", unid: "un", porPessoa: 0.092 },
    ],
  },
  {
    nome: "Churrasco de Panela de Pressão",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "pct", porPessoa: 0.031, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.077 },
      { item: "Pimentão verde", unid: "kg", porPessoa: 0.031 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "churrasco na panela de pressão",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.615 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Batata", unid: "kg", porPessoa: 0.092 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.154 },
      { item: "Maionese", unid: "un", porPessoa: 0.015 },
      { item: "Limão", unid: "kg", porPessoa: 0.031 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
      { item: "Creme de Leite", unid: "lt", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Costela ao molho de Barbecue",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.031 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Repolho", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
      { item: "Brocolis", unid: "un", porPessoa: 0.123 },
    ],
  },
  {
    nome: "Costela Assada com Mandioca",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.462 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.185 },
      { item: "Creme culinário", unid: "lt", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Costela Bovina",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Couve na manteiga", unid: "un", porPessoa: 0.154 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Creme de Leite", unid: "lt", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Costela Bovina Assada",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Abóbora", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Costela Bovina com Batata",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031, opcional: true },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015, opcional: true },
      { item: "Chuchu", unid: "kg", porPessoa: 0.077, opcional: true },
    ],
  },
  {
    nome: "Costela Bovina com Mandioca",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.077 },
      { item: "Batata doce", unid: "kg", porPessoa: 0.092 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.031 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
      { item: "Couve", unid: "un", porPessoa: 0.062 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.092 },
    ],
  },
  {
    nome: "Costela Bovina no forno com Mandioca",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Abóbora", unid: "un", porPessoa: 0.062 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Pepino", unid: "kg", porPessoa: 0.031 },
      { item: "Curau", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Costela no Forno",
    categoria: "principal",
    rendimento: 65,
    ingredientes: [
      { item: "Abóbora", unid: "un", porPessoa: 0.031 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.062 },
      { item: "Pepino comum", unid: "kg", porPessoa: 0.031 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Pudim de coco", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Costelinha com Barbacue",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Farinha", unid: "kg", porPessoa: 0.046 },
      { item: "Alface", unid: "un", porPessoa: 0.062 },
      { item: "Pepino", unid: "kg", porPessoa: 0.031 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Gelatina", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Costelinha com Barbecue",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Barbecue", unid: "lt", porPessoa: 0.015 },
      { item: "Couve", unid: "un", porPessoa: 0.092 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Costelinha Suina Acebolado",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.154 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.108 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.092 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
      { item: "Limão", unid: "un", porPessoa: 0.154 },
    ],
  },
  {
    nome: "Costelinha Suina c/ Limão na Pressão",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.077 },
      { item: "Limão", unid: "un", porPessoa: 0.092 },
      { item: "Abobrinha", unid: "kg", porPessoa: 0.123 },
    ],
  },
  {
    nome: "Costelinha Suina com Barbecue",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Molho barbecue", unid: "un", porPessoa: 0.015 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.138 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
      { item: "Abacaxi madura", unid: "un", porPessoa: 0.062 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
      { item: "Barbecue", unid: "un", porPessoa: 0.015 },
      { item: "Farinha torrada de mandioca", unid: "pct", porPessoa: 0.015 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.108 },
    ],
  },
  {
    nome: "Costelinha Suína na Manteiga",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Manteiga", unid: "pct", porPessoa: 0.015 },
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
      { item: "Mousse de Maracujá", unid: "pct", porPessoa: 0.015 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "costelinha suina/ Chuleta Bovina",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.015 },
      { item: "Feijão Fraldinha-", unid: "kg", porPessoa: 0.062 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.108 },
      { item: "Bacon-", unid: "pç", porPessoa: 0.015 },
      { item: "Cenoura-", unid: "kg", porPessoa: 0.046 },
      { item: "Batata-", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Coxa Assada",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Coxa e Sobre Coxa Assada",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Mandioca Descascada", unid: "kg", porPessoa: 0.046 },
      { item: "Leite", unid: "lt", porPessoa: 0.015 },
      { item: "Acelga", unid: "un", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
      { item: "Abacate maduro", unid: "un", porPessoa: 0.062 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Coxa e Sobre Coxa com mandioca assada",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Rucula", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Flany Baunilha", unid: "pct", porPessoa: 0.015 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.077 },
      { item: "Macarrão", unid: "pct", porPessoa: 0.123 },
    ],
  },
  {
    nome: "Coxa e Sobrecoxa",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.538 },
      { item: "Batata", unid: "kg", porPessoa: 0.154 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Maionese", unid: "un", porPessoa: 0.015 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.138 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Coxa e Sobrecoxa assada",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Alface", unid: "un", porPessoa: 0.123 },
      { item: "Pepino japonês", unid: "kg", porPessoa: 0.046 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Cubos de Frango Refolgada",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Abóbora", unid: "un", porPessoa: 0.046 },
      { item: "Alface", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
      { item: "Leite", unid: "lt", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Escondidinho de Carne",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Batata Palha", unid: "pct", porPessoa: 0.031 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031, opcional: true },
      { item: "Alface crespa", unid: "un", porPessoa: 0.092, opcional: true },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046, opcional: true },
      { item: "Alface lisa", unid: "un", porPessoa: 0.077, opcional: true },
    ],
  },
  {
    nome: "Escondidinho de carne moída",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
    ],
  },
  {
    nome: "Escondidinho de Frango",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.231 },
      { item: "Purê de batata", unid: "un", porPessoa: 0.031 },
      { item: "Batata Palha", unid: "pct", porPessoa: 0.031 },
      { item: "Mussarela", unid: "pç", porPessoa: 0.031, opcional: true },
      { item: "Creme culinário", unid: "pct", porPessoa: 0.031, opcional: true },
      { item: "Alface lisa", unid: "un", porPessoa: 0.092 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Pepino", unid: "kg", porPessoa: 0.046, opcional: true },
    ],
  },
  {
    nome: "Espaguete ao molho de tomate com almôndegas",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Espaguete", unid: "pct", porPessoa: 0.077 },
      { item: "Repolho", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Feijão Tropeiro com Bisteca",
    categoria: "principal",
    rendimento: 65,
    ingredientes: [
      { item: "Feijão Fraldinho", unid: "kg", porPessoa: 0.046 },
      { item: "Banana da Terra madura", unid: "un", porPessoa: 0.462 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.154 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Batata", unid: "kg", porPessoa: 0.092 },
      { item: "Farinha de mandioca", unid: "pct", porPessoa: 0.046 },
      { item: "Maionese", unid: "un", porPessoa: 0.015 },
      { item: "Feijão fradinho", unid: "kg", porPessoa: 0.062 },
      { item: "Canjica", unid: "pct", porPessoa: 0.031 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Feijão Tropeiro com Costelinha Suina",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Feijão Fraldinha", unid: "kg", porPessoa: 0.046 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.154 },
      { item: "Mousse de Morango", unid: "pct", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Feijão Tropeiro com Lombo suino",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Feijão Fraldinho", unid: "kg", porPessoa: 0.062 },
      { item: "Banana da Terra madura", unid: "un", porPessoa: 0.369 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.154 },
      { item: "Flan de Baunilha", unid: "pct", porPessoa: 0.015 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Bacon", unid: "kg", porPessoa: 0.062 },
      { item: "Alface americano", unid: "un", porPessoa: 0.123 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.092 },
      { item: "Feijão fradinho", unid: "kg", porPessoa: 0.077 },
      { item: "Pudim", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Feijoada com Bisteca",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.015 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Couve", unid: "un", porPessoa: 0.231, opcional: true },
      { item: "Abacaxi", unid: "un", porPessoa: 0.138 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.231, opcional: true },
      { item: "Feijao Preto", unid: "kg", porPessoa: 0.062, opcional: true },
    ],
  },
  {
    nome: "Feijoada com Costelinha",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.108, opcional: true },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.108 },
      { item: "Cebola", unid: "kg", porPessoa: 0.015, opcional: true },
    ],
  },
  {
    nome: "Feijoada com Costelinha de Porco",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Feijao Preto", unid: "kg", porPessoa: 0.062 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Couve", unid: "un", porPessoa: 0.123 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.138 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Feijoada com costelinha suína",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.154 },
      { item: "Couve", unid: "un", porPessoa: 0.123 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.108 },
    ],
  },
  {
    nome: "Feijoada com lombo de porco",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Couve", unid: "un", porPessoa: 0.092 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.092 },
    ],
  },
  {
    nome: "Feijoada com Lombo suino",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Feijao Preto", unid: "kg", porPessoa: 0.062 },
      { item: "Couve", unid: "un", porPessoa: 0.092 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Abacaxi precisa vim maduro", unid: "un", porPessoa: 0.092 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Feijoada com Pernil de Porco",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.138 },
      { item: "Feijao Preto", unid: "kg", porPessoa: 0.062 },
      { item: "Couve", unid: "un", porPessoa: 0.123 },
    ],
  },
  {
    nome: "Feijoada Completa com Costelinha",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Calabresa", unid: "un", porPessoa: 0.015 },
      { item: "Farinha de mandioca", unid: "pct", porPessoa: 0.015 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.154 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.138 },
    ],
  },
  {
    nome: "Feijoada simples com costelinha de porco e Bacon",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Feijao Preto", unid: "kg", porPessoa: 0.062 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Pepino japonês", unid: "kg", porPessoa: 0.046 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.092 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.154 },
    ],
  },
  {
    nome: "File a Parmegiana de Frango",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.231 },
      { item: "Pure de Batata-", unid: "pct", porPessoa: 0.015 },
      { item: "Alface Americano-", unid: "un", porPessoa: 0.108 },
      { item: "Manga-", unid: "un", porPessoa: 0.077 },
      { item: "Coco Ralado-", unid: "pct", porPessoa: 0.015 },
      { item: "Leite condensado-", unid: "bag", porPessoa: 0.015 },
      { item: "Creme Culinário-", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "File de Coxa Acebolado",
    categoria: "principal",
    rendimento: 65,
    ingredientes: [
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Milho verde", unid: "lata", porPessoa: 0.031 },
      { item: "Pepino", unid: "kg", porPessoa: 0.046 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.046 },
      { item: "Pudim", unid: "pct", porPessoa: 0.015 },
      { item: "Alface lisa", unid: "un", porPessoa: 0.092 },
    ],
  },
  {
    nome: "Filé de frango",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Filé de peito", unid: "kg", porPessoa: 0.308 },
      { item: "Milho", unid: "lata", porPessoa: 0.015 },
      { item: "Alface americana", unid: "un", porPessoa: 0.108 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Suco de limão", unid: "pct", porPessoa: 0.015 },
      { item: "Creme de Leite", unid: "lt", porPessoa: 0.031 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
    ],
  },
  {
    nome: "File de Frango á Milanesa",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Purê de batata", unid: "pct", porPessoa: 0.031 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.108 },
      { item: "Tomate", unid: "kg", porPessoa: 0.077 },
      { item: "Pudim de coco", unid: "pct", porPessoa: 0.015 },
      { item: "Mousse de chocolate", unid: "pct", porPessoa: 0.015 },
      { item: "Farinha para empanar", unid: "un", porPessoa: 0.062 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.077 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.046 },
    ],
  },
  {
    nome: "File de Frango a Parmegiana",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Abóbora", unid: "kg", porPessoa: 0.092 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.108 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.015 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.138 },
    ],
  },
  {
    nome: "File de Frango a Pizzaiolo",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.031 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
      { item: "Melancia", unid: "un", porPessoa: 0.031, opcional: true },
      { item: "Milho", unid: "un", porPessoa: 0.015, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Pepino", unid: "kg", porPessoa: 0.046, opcional: true },
    ],
  },
  {
    nome: "File de Frango á Pizzaiolo com manjerição",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Manjericão", unid: "mç", porPessoa: 0.769 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.031 },
      { item: "Berinjela comum", unid: "kg", porPessoa: 0.046 },
      { item: "Alface americano", unid: "un", porPessoa: 0.077 },
      { item: "Manga", unid: "un", porPessoa: 0.046 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.015 },
      { item: "Macarrão parafuso", unid: "un", porPessoa: 0.123 },
      { item: "Milho", unid: "lata", porPessoa: 0.015 },
      { item: "Maionese", unid: "un", porPessoa: 0.015 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
      { item: "Salsinha", unid: "mç", porPessoa: 0.015 },
      { item: "Cebolinha", unid: "mç", porPessoa: 0.015 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "File de Frango Acebolado",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046, opcional: true },
      { item: "Milho verde", unid: "lata", porPessoa: 0.031, opcional: true },
      { item: "Beterraba", unid: "kg", porPessoa: 0.046, opcional: true },
      { item: "Leite", unid: "lt", porPessoa: 0.046, opcional: true },
      { item: "Creme culinário", unid: "lt", porPessoa: 0.046, opcional: true },
    ],
  },
  {
    nome: "Filé de frango ao molho de tomate (filé de coxa)",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Repolho", unid: "un", porPessoa: 0.062 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.077 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Molho de tomate", unid: "lt", porPessoa: 0.046 },
    ],
  },
  {
    nome: "File de Frango ao molho Madeira",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Macarrão Spaguetti", unid: "pct", porPessoa: 0.123 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.062 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "File de frango com bacon",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.185 },
      { item: "Bacon-", unid: "pç", porPessoa: 0.015 },
      { item: "Macarrão Spaguetti-", unid: "un", porPessoa: 0.123 },
      { item: "Abobrinha-", unid: "kg", porPessoa: 0.062 },
      { item: "Suco de maracuja-", unid: "un", porPessoa: 0.015 },
      { item: "Creme Culinário-", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Filé de frango em tiras com legumes",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Brocolis Ninja", unid: "un", porPessoa: 0.092 },
      { item: "Macarrão espaguete", unid: "un", porPessoa: 0.092 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.046 },
      { item: "Gelatina", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Filé de Frango Empanado",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Repolho", unid: "bag", porPessoa: 0.015 },
      { item: "Couve flor", unid: "kg", porPessoa: 0.123 },
      { item: "Brocolis", unid: "un", porPessoa: 0.123 },
      { item: "Farinha de Empanar", unid: "un", porPessoa: 0.015 },
      { item: "Leite Condensadon", unid: "un", porPessoa: 0.015 },
      { item: "Suco de Frambeosa", unid: "Um", porPessoa: 0.015 },
      { item: "Creme culinário", unid: "Um", porPessoa: 0.015 },
    ],
  },
  {
    nome: "File de Frango Grelhado",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura-", unid: "kg", porPessoa: 0.062, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "File de Frango Parmegiana",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.015 },
      { item: "Molho de tomate", unid: "lt", porPessoa: 0.046 },
      { item: "Alface americano", unid: "un", porPessoa: 0.154, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "File de Frango Pizzaiolo com manjerição",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Couve", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Batata doce", unid: "kg", porPessoa: 0.077 },
      { item: "Manjericão", unid: "g", porPessoa: 1.538 },
      { item: "Extrato de tomate", unid: "lt", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Filé de peito de frango grelhado",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Abóbora japonesa", unid: "un", porPessoa: 0.046 },
      { item: "Rucula", unid: "un", porPessoa: 0.108 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "File de peixe ao molho Tártaro",
    categoria: "principal",
    proteina: "peixe",
    rendimento: 65,
    ingredientes: [
      { item: "File de Panga", unid: "kg", porPessoa: 0.231 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Batata", unid: "kg", porPessoa: 0.031 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.046 },
      { item: "Alface lisa", unid: "un", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "File Parmegiana de Frango",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.015 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Frango á jardineira",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.231 },
      { item: "Milho", unid: "lata", porPessoa: 0.015 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Batata", unid: "kg", porPessoa: 0.046 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.031 },
      { item: "Gelatina", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Frango à milanesa",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Batata congelada", unid: "kg", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.077 },
      { item: "Pimentão verde", unid: "kg", porPessoa: 0.031 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
      { item: "gelatina incolor", unid: "pct", porPessoa: 0.015 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
      { item: "Creme de Leite", unid: "lt", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Frango a passarinho",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Batata", unid: "kg", porPessoa: 0.092 },
    ],
  },
  {
    nome: "Frango á Passarinho ao molho Tártaro",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Limão", unid: "un", porPessoa: 0.154 },
      { item: "Maionsese", unid: "un", porPessoa: 0.015 },
      { item: "Repolho", unid: "un", porPessoa: 0.046 },
      { item: "Maçã", unid: "un", porPessoa: 0.092 },
      { item: "Pudim de coco", unid: "pct", porPessoa: 0.015 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Frango à Pizzaiolo",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.062 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Frango a xadrez com Brocolis e Cenoura",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Brocolis", unid: "un", porPessoa: 0.062 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Pepino", unid: "kg", porPessoa: 0.062 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Macarrão", unid: "pct", porPessoa: 0.123 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
      { item: "Shoyu", unid: "lt", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Frango Assado",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.138 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Maionese", unid: "un", porPessoa: 0.015, opcional: true },
    ],
  },
  {
    nome: "Frango Assado com bacon",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.108 },
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Maionese", unid: "un", porPessoa: 0.015 },
      { item: "Flany Baunilha", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Frango Assado com Batata",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.138 },
      { item: "Batata-", unid: "kg", porPessoa: 0.077 },
      { item: "Farinha de mandioca-", unid: "kg", porPessoa: 0.046 },
      { item: "Macarrão Parafuso-", unid: "pct", porPessoa: 0.062 },
      { item: "Milho Verde-", unid: "un", porPessoa: 0.015 },
      { item: "Cenoura-", unid: "kg", porPessoa: 0.031 },
      { item: "Maionese-", unid: "un", porPessoa: 0.015 },
      { item: "coentro", unid: "mç", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Frango assado com Linguiça",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.123 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Maionese", unid: "un", porPessoa: 0.015 },
      { item: "Mousse Chocolate", unid: "pct", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Frango Cozido",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.138 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.046 },
      { item: "Fuba", unid: "kg", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Frango Cozido com legumes",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Alface", unid: "un", porPessoa: 0.123, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.046, opcional: true },
      { item: "Acelga", unid: "un", porPessoa: 0.046, opcional: true },
    ],
  },
  {
    nome: "Frango Cremoso",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Macarrão Spaguetti-", unid: "un", porPessoa: 0.123 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.046 },
      { item: "Pepino comum-", unid: "kg", porPessoa: 0.046 },
      { item: "Tomate-", unid: "kg", porPessoa: 0.046 },
      { item: "Gelatina-", unid: "un", porPessoa: 0.015 },
      { item: "Leite condensado-", unid: "bag", porPessoa: 0.015 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.046 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Macarrão", unid: "pct", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Frango Desfiado",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.231 },
      { item: "Batata doce", unid: "kg", porPessoa: 0.092 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Batata", unid: "kg", porPessoa: 0.046 },
      { item: "Leite", unid: "un", porPessoa: 0.015 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.015 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Alface americano", unid: "un", porPessoa: 0.123 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Frango Desfiado com Milho",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Milho", unid: "lata", porPessoa: 0.015 },
      { item: "Batata doce", unid: "kg", porPessoa: 0.077 },
    ],
  },
  {
    nome: "Frango em Cubos ao molho",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.031 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.077 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
      { item: "Pudim de coco", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Frango em cubos ao molho de tomate e cebola",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Repolho", unid: "un", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
      { item: "Coco Ralado-", unid: "pct", porPessoa: 0.015 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Frango grelhado com creme de milho",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Milho", unid: "lata", porPessoa: 0.031 },
      { item: "Creme culinário", unid: "pct", porPessoa: 0.015 },
      { item: "Alface americano", unid: "un", porPessoa: 0.077 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Suco de maracujá", unid: "pct", porPessoa: 0.015 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Frango Xadrez com Brocolis e cenoura",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Macarrão Spaguetti", unid: "un", porPessoa: 0.123, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.031, opcional: true },
      { item: "Beterraba", unid: "kg", porPessoa: 0.046, opcional: true },
      { item: "Brocolis", unid: "un", porPessoa: 0.062, opcional: true },
      { item: "Shoyu", unid: "ml", porPessoa: 0.015, opcional: true },
    ],
  },
  {
    nome: "Fricassê de Frango",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.231 },
      { item: "osso", unid: "kg", porPessoa: 0.231 },
      { item: "Queijo Mussarela", unid: "kg", porPessoa: 0.031 },
      { item: "Batata Palha", unid: "pct", porPessoa: 0.031 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.077 },
      { item: "Repolho", unid: "un", porPessoa: 0.015 },
      { item: "Alface", unid: "un", porPessoa: 0.046 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Leite Condesado", unid: "bag", porPessoa: 0.015 },
      { item: "Creme culinário", unid: "pct", porPessoa: 0.015 },
      { item: "Milho verde", unid: "lata", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Galinhada + Farofa",
    categoria: "principal",
    rendimento: 65,
    ingredientes: [
      { item: "Beterraba", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Bacon", unid: "pct", porPessoa: 0.015 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
      { item: "Leite", unid: "lt", porPessoa: 0.031 },
      { item: "coentro", unid: "mç", porPessoa: 0.015 },
      { item: "Pimentão", unid: "kg", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Isca de Peixe com molho de Limão",
    categoria: "principal",
    proteina: "peixe",
    rendimento: 65,
    ingredientes: [
      { item: "File de Panga", unid: "kg", porPessoa: 0.154 },
      { item: "Limão", unid: "un", porPessoa: 0.154 },
      { item: "Tomate", unid: "kg", porPessoa: 0.077 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
      { item: "Pimentão verde", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Milho", unid: "lata", porPessoa: 0.015 },
      { item: "Salsa", unid: "mç", porPessoa: 0.015 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Iscas de Carne no molho Shoyu",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
      { item: "Repolho", unid: "un", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Iscas de Frango com Bacon",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.046 },
      { item: "Batata", unid: "kg", porPessoa: 0.046 },
      { item: "Banana", unid: "un", porPessoa: 0.185 },
      { item: "Bolacha maisena", unid: "pct", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Iscas de peixe com molho de limão",
    categoria: "principal",
    proteina: "peixe",
    rendimento: 65,
    ingredientes: [
      { item: "File de Panga", unid: "kg", porPessoa: 0.154 },
      { item: "Limão", unid: "un", porPessoa: 0.154 },
      { item: "Tomate", unid: "kg", porPessoa: 0.077 },
      { item: "Pimentão verde", unid: "kg", porPessoa: 0.031 },
      { item: "Abacate", unid: "un", porPessoa: 0.077 },
      { item: "Brocolis", unid: "un", porPessoa: 0.046 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Lasanha a Bolonhesa",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.092, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Lasanha de Berinjela ( Para quem não come berinjela pode solicitar ovos)",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.077 },
      { item: "Berinjela", unid: "kg", porPessoa: 0.077 },
      { item: "Molho de tomate", unid: "lt", porPessoa: 0.046 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031 },
      { item: "Alface lisa", unid: "un", porPessoa: 0.092 },
      { item: "Pepino", unid: "kg", porPessoa: 0.031 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Lasanha de Frango",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.231 },
      { item: "Massa de lasanha", unid: "un", porPessoa: 0.062 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.046, opcional: true },
      { item: "Creme culinário", unid: "un", porPessoa: 0.062, opcional: true },
      { item: "Alface crespa", unid: "un", porPessoa: 0.092, opcional: true },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015, opcional: true },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015, opcional: true },
    ],
  },
  {
    nome: "Lasanha de Panela",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Massa de lasanha", unid: "pct", porPessoa: 0.062, opcional: true },
      { item: "Molho de tomate", unid: "lt", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031, opcional: true },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015, opcional: true },
    ],
  },
  {
    nome: "Lasanha de panela á Bolonhesa",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.154 },
      { item: "Massa de lasanha", unid: "un", porPessoa: 0.046 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.046 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.046 },
      { item: "Alface americano", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.015 },
      { item: "Cebola", unid: "kg", porPessoa: 0.015 },
      { item: "Pudim", unid: "pct", porPessoa: 0.015 },
      { item: "Alface lisa", unid: "un", porPessoa: 0.062 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.046 },
      { item: "Couve", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "LInguiça ao Forno",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
      { item: "Melão", unid: "un", porPessoa: 0.092 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.015 },
      { item: "Leite", unid: "lt", porPessoa: 0.015 },
      { item: "Acelga", unid: "un", porPessoa: 0.046 },
      { item: "Mexerica", unid: "un", porPessoa: 0.923 },
    ],
  },
  {
    nome: "Linguiça toscana assada com batata, cebola e pimentão",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Pimentão", unid: "kg", porPessoa: 0.062 },
      { item: "Tomate", unid: "kg", porPessoa: 0.092 },
      { item: "Cebola", unid: "kg", porPessoa: 0.092 },
      { item: "Goiaba", unid: "un", porPessoa: 0.923 },
    ],
  },
  {
    nome: "Linguiça Toscana no Forno",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Acelga", unid: "un", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Linguiça Toscana no Forno com a queijo",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Purê de batata", unid: "kg", porPessoa: 0.031 },
      { item: "Mussarela", unid: "pç", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Lombo suíno",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.154 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.062 },
      { item: "Suco de limão", unid: "pct", porPessoa: 0.015 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.046 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Lombo suino ao molho Barbecue",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Barbecue", unid: "un", porPessoa: 0.015 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
      { item: "Pimentão verde", unid: "kg", porPessoa: 0.031 },
      { item: "Mousse de Chocolate( Pronto)", unid: "pct", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Lombo suino Assado com abacaxi",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.046 },
      { item: "Pepino", unid: "kg", porPessoa: 0.062 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Milho", unid: "lata", porPessoa: 0.015 },
      { item: "Salsa", unid: "mç", porPessoa: 0.015 },
      { item: "Abacate", unid: "un", porPessoa: 0.077 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Lombo Suino com Abacaxi",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.062 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.046, opcional: true },
    ],
  },
  {
    nome: "Macarrão Al Pesto com desfiado (Frango à parte)",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Macarrão", unid: "pct", porPessoa: 0.154 },
      { item: "Parmesão Ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Manjericão", unid: "mç", porPessoa: 0.015 },
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Mousse de Morango", unid: "un", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Goiaba", unid: "un", porPessoa: 0.692 },
    ],
  },
  {
    nome: "Macarrão ao molho branco (bechamel) com almôndegas e à parte frango desfiado",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Macarrão", unid: "pct", porPessoa: 0.154 },
      { item: "Repolho", unid: "un", porPessoa: 0.031 },
      { item: "Acelga", unid: "un", porPessoa: 0.031 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
      { item: "farinha de trigo", unid: "kg", porPessoa: 0.015 },
      { item: "Parmesão", unid: "pct", porPessoa: 0.015 },
      { item: "Leite", unid: "lt", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Macarrão com Almondega",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.077 },
      { item: "Espaguete", unid: "pct", porPessoa: 0.154 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.046 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.138 },
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Maionese", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Macarrão com Molho de Almondegas",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Macarrão Spaguetti", unid: "un", porPessoa: 0.138 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.046 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.015 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.092 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Banana", unid: "un", porPessoa: 0.185 },
      { item: "Creme de Leite", unid: "un", porPessoa: 0.015 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Moqueca de Peixe",
    categoria: "principal",
    proteina: "peixe",
    rendimento: 65,
    ingredientes: [
      { item: "File de Panga", unid: "kg", porPessoa: 0.308 },
      { item: "Alface americano", unid: "un", porPessoa: 0.123 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Banana", unid: "un", porPessoa: 0.092 },
      { item: "Leite de coco", unid: "lt", porPessoa: 0.046 },
      { item: "Guento", unid: "mç", porPessoa: 0.015 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046 },
      { item: "Mousse de Morango", unid: "pct", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Omelete ao Forno ( Tomate, Cebola e Mussarela)",
    categoria: "principal",
    rendimento: 65,
    ingredientes: [
      { item: "Ovos", unid: "un", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031 },
      { item: "Brocolis", unid: "un", porPessoa: 0.077 },
      { item: "Couve flor", unid: "un", porPessoa: 0.077 },
      { item: "Agrião", unid: "un", porPessoa: 0.123 },
      { item: "Pepino", unid: "kg", porPessoa: 0.031 },
      { item: "Melancia", unid: "un", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Parmegiana de Frango",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Fritas", unid: "kg", porPessoa: 0.077 },
      { item: "Alface americano", unid: "un", porPessoa: 0.077 },
      { item: "Manga", unid: "un", porPessoa: 0.092 },
      { item: "Melão", unid: "un", porPessoa: 0.092 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.031 },
      { item: "Mussarela", unid: "kg", porPessoa: 0.031 },
      { item: "Farinha de Empanar", unid: "un", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Pernil Assado",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Brocolis", unid: "un", porPessoa: 0.062 },
      { item: "Beterraba", unid: "kg", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Gelatina Framboesa", unid: "pct", porPessoa: 0.015 },
      { item: "Macarrão", unid: "pct", porPessoa: 0.154 },
      { item: "Alface lisa", unid: "un", porPessoa: 0.108 },
    ],
  },
  {
    nome: "Pernil Assado com Abacaxi",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.308 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.062 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Batata", unid: "kg", porPessoa: 0.031 },
      { item: "Milho", unid: "un", porPessoa: 0.015 },
      { item: "Repolho", unid: "un", porPessoa: 0.031 },
      { item: "Batata Palha", unid: "pct", porPessoa: 0.015 },
      { item: "Maionese", unid: "un", porPessoa: 0.015 },
      { item: "Leite", unid: "lt", porPessoa: 0.015 },
      { item: "Cebola", unid: "kg", porPessoa: 0.015 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.046 },
      { item: "Pudim", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Pernil Suino Assado com molho de Limão",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Limão", unid: "un", porPessoa: 0.154 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.015 },
      { item: "Tomate", unid: "kg", porPessoa: 0.077 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
      { item: "Pimentão verde", unid: "kg", porPessoa: 0.031 },
      { item: "Abacaxi maduro", unid: "un", porPessoa: 0.123 },
    ],
  },
  {
    nome: "Picadinho",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.615 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.092 },
      { item: "Batata", unid: "kg", porPessoa: 0.154 },
      { item: "Alface", unid: "un", porPessoa: 0.077 },
      { item: "Gelatina", unid: "pct", porPessoa: 0.015 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Picadinho com Cenoura",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Repolho", unid: "un", porPessoa: 0.062, opcional: true },
    ],
  },
  {
    nome: "Picadinho com Cenoura e Batata",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Agrião", unid: "un", porPessoa: 0.092 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Picadinho com Cenoura e Chuchu",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.062 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.031 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
      { item: "Abacaxi", unid: "un", porPessoa: 0.092 },
      { item: "Farinha de mandioca", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Picadinho com chuchu",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.062 },
      { item: "Repolho", unid: "un", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Cebola roxa", unid: "kg", porPessoa: 0.031 },
      { item: "Pimentão verde", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Picadinho com legumes",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.046, opcional: true },
      { item: "Beterraba", unid: "kg", porPessoa: 0.031, opcional: true },
      { item: "Chuchu", unid: "kg", porPessoa: 0.046 },
      { item: "Leite condensado", unid: "un", porPessoa: 0.031, opcional: true },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.154, opcional: true },
    ],
  },
  {
    nome: "Rabada ao molho",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Rabada bovina", unid: "kg", porPessoa: 0.308 },
      { item: "Farinha de mandioca", unid: "kg", porPessoa: 0.031 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
      { item: "Batata", unid: "kg", porPessoa: 0.062 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Sobre coxa Assada",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.015, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Batata", unid: "kg", porPessoa: 0.077, opcional: true },
    ],
  },
  {
    nome: "SobreCoxa Assada",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Batata", unid: "kg", porPessoa: 0.092 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Sopa cremosa de mandioca com frango com batata e cenoura",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.062 },
      { item: "Mandioca", unid: "kg", porPessoa: 0.077 },
      { item: "Batata", unid: "kg", porPessoa: 0.046 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.046 },
      { item: "Alface", unid: "un", porPessoa: 0.077 },
      { item: "Mamão", unid: "un", porPessoa: 0.077 },
      { item: "Banana", unid: "un", porPessoa: 0.385 },
      { item: "Laranja", unid: "un", porPessoa: 0.185 },
      { item: "Maçã", unid: "un", porPessoa: 0.092 },
    ],
  },
  {
    nome: "ssê de Carne",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.231 },
      { item: "Pure de Batata-", unid: "pct", porPessoa: 0.031 },
      { item: "Batata doce-", unid: "kg", porPessoa: 0.092 },
      { item: "Couve manteiga-", unid: "kg", porPessoa: 0.092 },
      { item: "Tomate-", unid: "kg", porPessoa: 0.046 },
      { item: "Pudim de coco-", unid: "pct", porPessoa: 0.015 },
    ],
  },
  {
    nome: "ssê de frango",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Batata", unid: "kg", porPessoa: 0.077, opcional: true },
      { item: "Milho", unid: "un", porPessoa: 0.015, opcional: true },
      { item: "Tomate", unid: "kg", porPessoa: 0.046, opcional: true },
    ],
  },
  {
    nome: "Strogonoff de Carne",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Batata Palha", unid: "pct", porPessoa: 0.062 },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031, opcional: true },
    ],
  },
  {
    nome: "Strogonoff de Frango",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
      { item: "Batata Palha", unid: "pct", porPessoa: 0.062, opcional: true },
      { item: "Creme culinário", unid: "un", porPessoa: 0.031, opcional: true },
    ],
  },
  {
    nome: "Tiras de Carne ao Molho",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Molho de tomate", unid: "un", porPessoa: 0.031 },
      { item: "Batata bolinha", unid: "kg", porPessoa: 0.077 },
      { item: "Repolho roxo", unid: "un", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
      { item: "Pudim de Morango", unid: "pct", porPessoa: 0.015 },
      { item: "Suco de morango", unid: "pct", porPessoa: 0.015 },
      { item: "coentro", unid: "mç", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Tiras de Carne com Cebola Caramelizada",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Cebola", unid: "kg", porPessoa: 0.031 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Tiras de carne com cebola e pimentão",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Tomate", unid: "kg", porPessoa: 0.031 },
      { item: "Chuchu", unid: "kg", porPessoa: 0.031 },
      { item: "Pimentão", unid: "kg", porPessoa: 0.015 },
    ],
  },
  {
    nome: "Tiras de Carnes ao Molho Madeira",
    categoria: "principal",
    proteina: "bovina",
    rendimento: 65,
    ingredientes: [
      { item: "Acém", unid: "kg", porPessoa: 0.308 },
      { item: "Farinha de mandioca-", unid: "kg", porPessoa: 0.046 },
      { item: "Alface crespa", unid: "un", porPessoa: 0.062 },
      { item: "Alface Lisa-", unid: "un", porPessoa: 0.046 },
      { item: "Pepino comum-", unid: "kg", porPessoa: 0.046 },
      { item: "Maça Fuji-", unid: "un", porPessoa: 1.231 },
      { item: "Molho madeira-", unid: "pct", porPessoa: 0.015 },
      { item: "Cenoura-", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Tiras de Frango com bacon",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.308 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Batata doce", unid: "kg", porPessoa: 0.077 },
      { item: "Repolho", unid: "un", porPessoa: 0.046 },
      { item: "Maçã", unid: "un", porPessoa: 0.092 },
      { item: "Coco ralado", unid: "pct", porPessoa: 0.015 },
      { item: "Leite", unid: "un", porPessoa: 0.015 },
      { item: "Leite condensado", unid: "bag", porPessoa: 0.015 },
      { item: "Macarrão", unid: "pct", porPessoa: 0.123 },
      { item: "Alface americano", unid: "un", porPessoa: 0.123 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
    ],
  },
  {
    nome: "Tiras de Frango Refolgada",
    categoria: "principal",
    proteina: "frango",
    rendimento: 65,
    ingredientes: [
      { item: "Tiras de frango", unid: "kg", porPessoa: 0.231 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
      { item: "Alface", unid: "un", porPessoa: 0.046 },
      { item: "Couve", unid: "un", porPessoa: 0.046 },
      { item: "Tomate", unid: "kg", porPessoa: 0.046 },
    ],
  },
  {
    nome: "Tiras de Peixe ao molho de limão",
    categoria: "principal",
    proteina: "peixe",
    rendimento: 65,
    ingredientes: [
      { item: "File de Panga", unid: "kg", porPessoa: 0.154 },
      { item: "Limão", unid: "un", porPessoa: 0.154 },
      { item: "Agrião", unid: "un", porPessoa: 0.108 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Cenoura", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Toscana ao forno com Batata",
    categoria: "principal",
    proteina: "suina",
    rendimento: 65,
    ingredientes: [
      { item: "Lombo suíno", unid: "kg", porPessoa: 0.231 },
      { item: "Batata", unid: "kg", porPessoa: 0.077 },
      { item: "Tomate", unid: "kg", porPessoa: 0.062 },
      { item: "Pimentão verde", unid: "kg", porPessoa: 0.031 },
      { item: "Cebola-", unid: "kg", porPessoa: 0.031 },
    ],
  },
  {
    nome: "Tutu de Feijão com Bisteca",
    categoria: "principal",
    rendimento: 65,
    ingredientes: [
      { item: "Banana da Terra madura", unid: "un", porPessoa: 0.369 },
      { item: "Couve manteiga", unid: "un", porPessoa: 0.138 },
      { item: "Feijão Carioca", unid: "kg", porPessoa: 0.031 },
      { item: "Bacon", unid: "pç", porPessoa: 0.015 },
      { item: "Couve", unid: "un", porPessoa: 0.138 },
      { item: "Suco de maracujá", unid: "pct", porPessoa: 0.015 },
      { item: "coentro", unid: "mç", porPessoa: 0.015 },
    ],
  },
];
